### ISSUE TITLE
对于首次接触的人，也要解决对未知的恐惧

### ISSUE THREAD

**Issue by cmheia** [Mark24Code/15minGit#5]
举个栗子：
第一天，小明创建了仅包含功1的文件main.cpp并创建remote repository；
第二天，李雷和韩梅梅各自clone到本地，李雷修改文件main.cpp添加了功能2，韩梅梅修改文件main.cpp添加了功能3；
第三天…… @Mark24Code 接

**Comment by Mark24Code** [comment]
解决冲突已经更新
