### ISSUE TITLE
推荐一个hg的教程

### ISSUE THREAD

**Issue by SyuTingSong** [Mark24Code/15minGit#6]
hg和git一样也是分布式版本管理系统。我当初是看着这个教程入门的，它有专门针对SVN用户的再教育环节。分布式版本管理系统看上去很复杂，但是如果能放弃为SVN找对应功能的心理，而是回归版本管理具体面对的问题，用案例完成教学就很容易理解和学会，值得参考一下。

http://hginit.com/

如果打不开可以访问我的mirror

http://lib.xts.so/mirror/hginit.com/

**Comment by Mark24Code** [comment]
非常感谢
